spring.application.name=helloservice

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=${spring.application.name}
